# Generated by Django 5.0.1 on 2024-09-17 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='API neve')),
                ('url', models.URLField(verbose_name='API URL')),
                ('description', models.TextField(blank=True, verbose_name='API leírása')),
            ],
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tanulási út neve')),
                ('value', models.CharField(max_length=100, verbose_name='Tanulási út értéke')),
            ],
            options={
                'verbose_name': 'Tanulási út',
                'verbose_name_plural': 'Tanulási utak',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Személyiség neve')),
                ('value', models.CharField(max_length=100, verbose_name='Személyiség értéke')),
            ],
            options={
                'verbose_name': 'Személyiség',
                'verbose_name_plural': 'Személyiségek',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Típus neve')),
                ('value', models.CharField(max_length=100, verbose_name='Típus értéke')),
            ],
            options={
                'verbose_name': 'Típus',
                'verbose_name_plural': 'Típusok',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modell neve')),
                ('apis', models.ManyToManyField(blank=True, to='adan.api', verbose_name='Kapcsolódó API-k')),
                ('learning_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.learningpath', verbose_name='Tanulási út')),
                ('personality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.personality', verbose_name='Személyiség')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.type', verbose_name='Típus')),
            ],
            options={
                'verbose_name': 'Modell',
                'verbose_name_plural': 'Modellek',
                'ordering': ['name'],
            },
        ),
    ]
