# Generated by Django 5.0.1 on 2024-09-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api',
            options={'ordering': ['name'], 'verbose_name': 'API', 'verbose_name_plural': 'API-k'},
        ),
        migrations.AddField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktív'),
        ),
    ]
