# Generated by Django 5.0.1 on 2024-09-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpath',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tanulási út neve'),
        ),
        migrations.AlterField(
            model_name='learningpath',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Tanulási út értéke'),
        ),
        migrations.AlterField(
            model_name='model',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.learningpath', verbose_name='Tanulási út'),
        ),
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Modell neve'),
        ),
        migrations.AlterField(
            model_name='model',
            name='personality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.personality', verbose_name='Személyiség'),
        ),
        migrations.AlterField(
            model_name='model',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adan.type', verbose_name='Típus'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Személyiség neve'),
        ),
        migrations.AlterField(
            model_name='personality',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Személyiség értéke'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Típus neve'),
        ),
        migrations.AlterField(
            model_name='type',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Típus értéke'),
        ),
    ]
