# Generated by Django 5.0.1 on 2024-09-16 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0002_alter_learningpath_name_alter_learningpath_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningpath',
            options={'ordering': ['name'], 'verbose_name': 'Tanulási út', 'verbose_name_plural': 'Tanulási utak'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name'], 'verbose_name': 'Modell', 'verbose_name_plural': 'Modellek'},
        ),
        migrations.AlterModelOptions(
            name='personality',
            options={'ordering': ['name'], 'verbose_name': 'Személyiség', 'verbose_name_plural': 'Személyiségek'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'Típus', 'verbose_name_plural': 'Típusok'},
        ),
    ]
