# Generated by Django 5.0.1 on 2024-09-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adan', '0003_alter_learningpath_options_alter_model_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktív'),
        ),
    ]
