# Generated by Django 5.0.1 on 2024-09-16 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='content',
            field=models.TextField(verbose_name='Tartalom'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='organization.employee', verbose_name='Küldő'),
        ),
        migrations.AlterField(
            model_name='email',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Küldés időpontja'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás időpontja'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_pages', to='organization.employee', verbose_name='Készítő'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='description',
            field=models.TextField(verbose_name='Leírás'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Cím'),
        ),
    ]
